"""Phase 56 - error-conditioned attention analysis package."""

from .analyses import (
    build_attention_arrays,
    build_continuous_matrix,
    compute_shared_cohort_layer_summary,
    build_target_id_to_idx,
    compute_continuous_associations,
    compute_cross_seed_layer_summary,
    compute_decile_metric_summary,
    compute_full_matrix_association,
    compute_high_low_metric_comparison,
    compute_high_low_profile,
    compute_layer_head_mean_association,
    compute_layer_head_mean_high_low,
    compute_layer_head_mean_metrics_long,
    compute_regime_composition,
    compute_signed_metric_comparison,
    compute_signed_profile,
    compute_worst_case_context,
)
from .cohort import CohortAssignmentResult, assign_seed_cohorts, build_cohort_assignment
from .core_metrics import (
    EPSILON_H,
    METRIC_FUNCS,
    LAG_MINUTES,
    compute_core_metrics_vector,
    expected_lag_minutes,
    lag80_minutes,
    normalized_entropy,
    recent_1h_mass,
    recent_6h_mass,
    top5_mass,
)
from .findings import (
    FINDING_CODES,
    build_discrepancies,
    build_findings,
    build_handoff_phase57,
    build_handoff_phase58,
    build_signoff,
    build_tests,
)
from .figures import (
    fig_01_abs_error_associations,
    fig_02_signed_residual_associations,
    fig_03_high_low_cliffs_delta,
    fig_04_layer_head_mean_associations,
    fig_05_high_vs_low_layer_head_mean_profiles,
    fig_06_high_minus_low_layer_diff,
    fig_07_error_decile_metric_trends,
    fig_08_error_decile_lag_bin_allocation,
    fig_09_under_vs_over_metrics,
    fig_10_under_vs_over_layer_profile,
    fig_11_shared_low_vs_shared_high_layer_profile,
    fig_12_full_matrix_association,
    fig_13_error_cohort_regime_composition,
    fig_14_worst_case_context,
)
from .joiner import JoinResult, join_attention_with_cohorts
from .metrics_utils import (
    cliffs_delta,
    cosine_similarity,
    jsd_natural_log,
    l1_distance,
    spearman_rho_safe,
    wasserstein_minutes,
)
from .orchestrator import PHASE56_VERSION, run_phase56
from .sources import (
    COHORT_EDGE_FRACTION,
    COHORT_RULE,
    CONDITIONING_VARIABLES,
    CORE_ATTENTION_METRICS_V1,
    DECILE_COUNT,
    FrozenSources56,
    FULL_MATRIX_METRICS,
    JSD_BOUNDS,
    LAG_STEP_MINUTES,
    NUM_HEADS,
    NUM_LAYERS,
    N_TEST,
    PROFILE_SUM_TOL,
    SEEDS,
    load_frozen_sources56,
)

__all__ = [
    "PHASE56_VERSION",
    "run_phase56",
    "SEEDS", "NUM_LAYERS", "NUM_HEADS", "N_TEST", "LOOKBACK",
    "CORE_ATTENTION_METRICS_V1",
    "CONDITIONING_VARIABLES",
    "COHORT_RULE", "COHORT_EDGE_FRACTION", "DECILE_COUNT",
    "JSD_BOUNDS", "PROFILE_SUM_TOL",
    "FULL_MATRIX_METRICS",
    "FrozenSources56", "load_frozen_sources56",
    "CohortAssignmentResult", "assign_seed_cohorts", "build_cohort_assignment",
    "JoinResult", "join_attention_with_cohorts",
    "LAG_MINUTES", "jsd_natural_log", "cosine_similarity", "l1_distance",
    "wasserstein_minutes", "cliffs_delta", "spearman_rho_safe",
    "EPSILON_H", "METRIC_FUNCS", "compute_core_metrics_vector",
    "normalized_entropy", "expected_lag_minutes", "lag80_minutes",
    "recent_1h_mass", "recent_6h_mass", "top5_mass",
    "compute_continuous_associations", "build_continuous_matrix",
    "compute_decile_metric_summary",
    "compute_high_low_metric_comparison", "compute_high_low_profile",
    "compute_signed_metric_comparison", "compute_signed_profile",
    "compute_layer_head_mean_metrics_long", "compute_layer_head_mean_association",
    "compute_layer_head_mean_high_low", "build_shared_cohort_layer_summary",
    "compute_cross_seed_layer_summary",
    "compute_full_matrix_association",
    "compute_regime_composition", "compute_worst_case_context",
    "build_attention_arrays", "build_target_id_to_idx",
    "fig_01_abs_error_associations", "fig_02_signed_residual_associations",
    "fig_03_high_low_cliffs_delta", "fig_04_layer_head_mean_associations",
    "fig_05_high_vs_low_layer_head_mean_profiles", "fig_06_high_minus_low_layer_diff",
    "fig_07_error_decile_metric_trends", "fig_08_error_decile_lag_bin_allocation",
    "fig_09_under_vs_over_metrics", "fig_10_under_vs_over_layer_profile",
    "fig_11_shared_low_vs_shared_high_layer_profile",
    "fig_12_full_matrix_association", "fig_13_error_cohort_regime_composition",
    "fig_14_worst_case_context",
    "FINDING_CODES", "build_findings", "build_discrepancies",
    "build_tests", "build_signoff",
    "build_handoff_phase57", "build_handoff_phase58",
]
