"""Phase 57 - findings, tests, handoffs, signoff generation."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from .sources import (
    ANCHOR_REASON,
    ANCHOR_SEED,
    MATCH_TIE_TOL,
    NUM_HEADS,
    NUM_LAYERS,
    PHASE52_VERSION,
    PHASE54_VERSION,
    PHASE55_VERSION,
    PHASE56_VERSION,
    PHASE57_VERSION,
    SEEDS,
)


def write_findings_csv(fp: Path, rows: List[dict]) -> int:
    import csv
    fp.parent.mkdir(parents=True, exist_ok=True)
    cols = ["finding_id", "scope", "seed", "layer", "head_if_applicable", "code", "value"]
    with fp.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(cols)
        for r in rows:
            w.writerow([r.get(c, "") for c in cols])
    return len(rows)


def write_tests_csv(fp: Path, rows: List[dict]) -> int:
    import csv
    fp.parent.mkdir(parents=True, exist_ok=True)
    cols = ["test_id", "scope", "check", "expected", "observed", "status"]
    with fp.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(cols)
        for r in rows:
            w.writerow([r.get(c, "") for c in cols])
    return len(rows)


def write_discrepancies_json(fp: Path, rows: List[dict]) -> None:
    fp.parent.mkdir(parents=True, exist_ok=True)
    fp.write_text(json.dumps({
        "total": len(rows),
        "items": rows,
        "status": "PASS" if len(rows) == 0 else "REVIEW",
    }, indent=2, ensure_ascii=False))


def write_phase58_handoff(
    fp: Path,
    layer_pair_summary: List[dict],
    matching_results: Dict,
    ambiguity_rows: List[dict],
    cycle_layer_summary: List[dict],
    wasserstein_summary: List[dict],
    matched_summary: List[dict],
    matched_metric_rows: List[dict],
    dense_summary: List[dict],
    error_layer_rows: List[dict],
    pred_assoc_rows: List[dict],
    evidence_rows: List[dict],
    sources,
) -> None:
    fp.parent.mkdir(parents=True, exist_ok=True)
    obj = {
        "phase": 57,
        "downstream_phase": 58,
        "downstream_name": "Final Tables",
        "source_phase57_version": PHASE57_VERSION,
        "source_phase56_version": PHASE56_VERSION,
        "source_phase55_version": PHASE55_VERSION,
        "source_phase54_version": PHASE54_VERSION,
        "source_phase53_version": "ATTENTION_HEATMAPS-v1",
        "source_phase52_version": PHASE52_VERSION,
        "final_lock_sha256": sources.final_lock_sha256,
        "test_population_sha256": sources.test_population_sha256,
        "phase47_canonical_test_population_sha256": sources.phase47_canonical_test_population_sha256,
        "phase52_attention_target_order_sha256": sources.phase52_attention_target_order_sha256,
        "raw_last_query_seed42_sha256": sources.raw_last_query_seed42_sha256,
        "raw_last_query_seed123_sha256": sources.raw_last_query_seed123_sha256,
        "raw_last_query_seed2026_sha256": sources.raw_last_query_seed2026_sha256,
        "seed_list": list(SEEDS),
        "anchor_seed": int(ANCHOR_SEED),
        "anchor_reason": ANCHOR_REASON,
        "performance_based_anchor": False,
        "layer_head_mean_stability_summary": layer_pair_summary,
        "head_matching_assignments": {
            f"L{l}__{a}__{b}": matching_results.get((l, a, b)).canonical_assignment
            for (l, a, b) in matching_results.keys()
        },
        "head_matching_ambiguity": ambiguity_rows,
        "cycle_consistency": cycle_layer_summary,
        "matching_sensitivity": wasserstein_summary,
        "matched_head_profile_stability_summary": matched_summary,
        "matched_head_metric_stability": matched_metric_rows,
        "dense_case_attention_stability_summary": dense_summary,
        "layer_error_conditioned_seed_stability": error_layer_rows,
        "prediction_attention_disagreement_association": pred_assoc_rows,
        "attention_seed_stability_evidence_summary": evidence_rows,
        "recommended_attention_tables": [
            "LAYER_TEMPORAL_PROFILE_SUMMARY",
            "HEAD_BEHAVIOR_COMPARISON",
            "ERROR_CONDITIONED_ATTENTION",
            "SEED_STABILITY_ATTENTION",
        ],
        "recommended_attention_figures": [
            "ATTENTION_HEATMAP",
            "LAST_QUERY_PROFILE",
            "ERROR_CONDITIONED_PROFILE",
            "SEED_STABILITY_PROFILE",
        ],
        "best_seed_selected": False,
        "best_head_selected": False,
        "causal_claim": False,
        "phase58_authorized": False,
        "phase59_authorized": False,
        "ready_for_phase58": True,
    }
    fp.write_text(json.dumps(obj, indent=2, ensure_ascii=False, default=str))


def write_phase59_context_handoff(
    fp: Path,
    findings_rows: List[dict],
    ambiguity_rows: List[dict],
    cycle_layer_summary: List[dict],
    wasserstein_summary: List[dict],
    error_layer_rows: List[dict],
    pred_assoc_rows: List[dict],
    sources,
) -> None:
    fp.parent.mkdir(parents=True, exist_ok=True)
    n_unanim = sum(1 for r in error_layer_rows if r.get("all_defined_same_sign"))
    obj = {
        "phase": 57,
        "downstream_phase": 59,
        "downstream_name": "Conclusions",
        "source_phase57_version": PHASE57_VERSION,
        "source_phase56_version": PHASE56_VERSION,
        "source_phase55_version": PHASE55_VERSION,
        "source_phase54_version": PHASE54_VERSION,
        "main_stability_findings": [
            r for r in findings_rows if r.get("code") in (
                "LAYER_HEAD_MEAN_PROFILES_HIGHLY_SIMILAR_DESCRIPTIVE",
                "LAYER_HEAD_MEAN_PROFILES_DIFFER_DESCRIPTIVELY",
                "LAYER_PER_TARGET_ATTENTION_STABLE_DESCRIPTIVE",
                "LAYER_PER_TARGET_ATTENTION_VARIABLE_DESCRIPTIVE",
                "MATCHED_HEAD_PROFILES_SIMILAR_DESCRIPTIVE",
                "MATCHED_HEAD_PROFILES_VARIABLE_DESCRIPTIVE",
            )
        ],
        "matching_limitations": [
            r for r in findings_rows if r.get("code") in ("HEAD_MATCHING_AMBIGUOUS",)
        ],
        "seed_variability_findings": [
            r for r in findings_rows if r.get("code") in ("HEAD_MATCHING_CYCLE_INCONSISTENT", "JSD_WASSERSTEIN_MATCHING_DIFFER")
        ],
        "error_attention_robustness_findings": [
            r for r in findings_rows if r.get("code") in (
                "ERROR_ATTENTION_SIGN_CONSISTENT_ACROSS_SEEDS",
                "ERROR_ATTENTION_SIGN_VARIES_ACROSS_SEEDS",
                "SHARED_COHORT_EFFECT_CONSISTENT_ACROSS_SEEDS",
                "SHARED_COHORT_EFFECT_VARIES_ACROSS_SEEDS",
            )
        ],
        "prediction_attention_disagreement_findings": [
            r for r in findings_rows if r.get("code") in (
                "PREDICTION_SPREAD_ASSOCIATED_WITH_ATTENTION_DISAGREEMENT",
                "NO_CLEAR_PREDICTION_ATTENTION_DISAGREEMENT_ASSOCIATION",
            )
        ],
        "attention_is_temporal_not_feature_importance": True,
        "attention_is_not_causal_explanation": True,
        "attention_stability_is_not_functional_equivalence": True,
        "three_seed_limit": True,
        "no_model_change_after_test": True,
        "phase58_authorized": False,
        "phase59_authorized": False,
        "ready_for_phase59_context": True,
    }
    fp.write_text(json.dumps(obj, indent=2, ensure_ascii=False, default=str))


def write_summary_json(
    fp: Path,
    sources,
    layer_pair_summary: List[dict],
    ambiguity_rows: List[dict],
    cycle_layer_summary: List[dict],
    wasserstein_summary: List[dict],
    matched_summary: List[dict],
    matched_per_target_summary: List[dict],
    dense_summary: List[dict],
    error_layer_rows: List[dict],
    pred_assoc_rows: List[dict],
    findings_rows: List[dict],
    overall_status: str,
) -> None:
    fp.parent.mkdir(parents=True, exist_ok=True)
    obj = {
        "version": PHASE57_VERSION,
        "corrective": True,
        "previous_version_archived": "SEED_STABILITY_ATTENTION-v1",
        "corrective_at_utc": datetime.now(timezone.utc).isoformat(),
        "source_phase56_version": PHASE56_VERSION,
        "source_phase55_version": PHASE55_VERSION,
        "source_phase54_version": PHASE54_VERSION,
        "source_phase52_version": PHASE52_VERSION,
        "final_lock_sha256": sources.final_lock_sha256,
        "test_population_sha256": sources.test_population_sha256,
        "phase47_canonical_test_population_sha256": sources.phase47_canonical_test_population_sha256,
        "phase52_attention_target_order_sha256": sources.phase52_attention_target_order_sha256,
        "raw_last_query_seed42_sha256": sources.raw_last_query_seed42_sha256,
        "raw_last_query_seed123_sha256": sources.raw_last_query_seed123_sha256,
        "raw_last_query_seed2026_sha256": sources.raw_last_query_seed2026_sha256,
        "seed_list": list(SEEDS),
        "anchor_seed": int(ANCHOR_SEED),
        "anchor_reason": ANCHOR_REASON,
        "layers": int(NUM_LAYERS),
        "heads": int(NUM_HEADS),
        "lookback": 72,
        "layer_stability_status": "OK",
        "per_target_layer_stability_status": "OK",
        "canonical_matching_status": "OK",
        "matching_ambiguity_summary": ambiguity_rows,
        "cycle_consistency_summary": cycle_layer_summary,
        "wasserstein_sensitivity_agreement": wasserstein_summary,
        "canonical_groups": len(matched_summary),
        "matched_head_profile_stability_status": "OK",
        "matched_head_per_target_stability_status": "OK",
        "dense_case_stability_status": "OK" if dense_summary else "NOT_APPLICABLE",
        "error_conditioned_layer_stability_status": "OK",
        "error_conditioned_matched_head_stability_status": "OK",
        "prediction_attention_disagreement_status": "OK",
        "findings": len(findings_rows),
        "best_seed_selected": False,
        "best_head_selected": False,
        "head_pruning": False,
        "model_retrained": False,
        "new_attention_extraction": False,
        "causal_claim": False,
        "phase58_ready": True,
        "phase59_context_ready": True,
        "phase58_authorized": False,
        "phase59_authorized": False,
        "overall_status": overall_status,
    }
    fp.write_text(json.dumps(obj, indent=2, ensure_ascii=False, default=str))


def write_signoff(
    fp: Path,
    sources,
    ambiguity_rows: List[dict],
    cycle_layer_summary: List[dict],
    wasserstein_summary: List[dict],
    matched_summary: List[dict],
    matched_per_target_summary: List[dict],
    dense_summary: List[dict],
    error_layer_rows: List[dict],
    pred_assoc_rows: List[dict],
    overall_status: str,
    warnings: List[str],
) -> None:
    fp.parent.mkdir(parents=True, exist_ok=True)
    obj = {
        "phase": 57,
        "phase_name": "Seed-stability attention check",
        "version": PHASE57_VERSION,
        "corrective": True,
        "previous_version_archived": "SEED_STABILITY_ATTENTION-v1",
        "corrective_at_utc": datetime.now(timezone.utc).isoformat(),
        "corrective_fixes": [
            "source_phase54_version: LAST_QUERY_ATTENTION-v1 -> v2",
            "source_phase55_version: HEAD_COMPARISON-v1 -> v2",
            "source_phase56_version: ERROR_CONDITIONED_ATTENTION-v1 -> v2",
            "final_lock_sha256: raw NPZ SHA 102086f7 -> canonical Phase45 combined lock 81fb87c4",
            "test_population_sha256: Phase52 attention target-order SHA c7039090 -> Phase47 canonical test population SHA d7dbc0b3",
            "raw_last_query_seed*_sha256 added as separate fields (seed42=102086f7, seed123=00e2f8e7, seed2026=34051966)",
            "phase52_attention_target_order_sha256 stored explicitly (= c7039090...)",
            "matched_head_metric_seed_stability.csv regenerated against Phase54 v2 metrics_long (NE rows now non-zero)",
            "layer_error_conditioned_seed_stability.csv regenerated against Phase56 v2 error_attention_association_long (NE rows now non-zero)",
            "matched_head_error_conditioned_stability.csv regenerated against Phase56 v2",
            "phase58_authorized=False and phase59_authorized=False flags added",
        ],
        "source_phase56_version": PHASE56_VERSION,
        "source_phase55_version": PHASE55_VERSION,
        "source_phase54_version": PHASE54_VERSION,
        "source_phase52_version": PHASE52_VERSION,
        "final_lock_sha256": sources.final_lock_sha256,
        "test_population_sha256": sources.test_population_sha256,
        "phase47_canonical_test_population_sha256": sources.phase47_canonical_test_population_sha256,
        "phase52_attention_target_order_sha256": sources.phase52_attention_target_order_sha256,
        "raw_last_query_seed42_sha256": sources.raw_last_query_seed42_sha256,
        "raw_last_query_seed123_sha256": sources.raw_last_query_seed123_sha256,
        "raw_last_query_seed2026_sha256": sources.raw_last_query_seed2026_sha256,
        "seed_list": list(SEEDS),
        "alignment_anchor_seed": int(ANCHOR_SEED),
        "anchor_reason": ANCHOR_REASON,
        "performance_based_anchor": False,
        "canonical_matching_cost": "JSD",
        "matching_method": "EXHAUSTIVE_PERMUTATION",
        "match_tie_tolerance": float(MATCH_TIE_TOL),
        "matching_sensitivity": "WASSERSTEIN_MINUTES",
        "layer_head_mean_stability_complete": True,
        "per_target_layer_stability_complete": True,
        "canonical_head_matching_complete": True,
        "matching_ambiguity_audit_complete": True,
        "cycle_consistency_complete": True,
        "matching_sensitivity_complete": True,
        "matched_head_profile_stability_complete": True,
        "matched_head_per_target_stability_complete": True,
        "matched_head_metric_stability_complete": True,
        "dense_case_stability_complete": bool(dense_summary),
        "error_conditioned_layer_stability_complete": True,
        "error_conditioned_matched_head_stability_complete": True,
        "prediction_attention_disagreement_complete": True,
        "matching_independent_of_error": True,
        "target_specific_rematching": False,
        "error_specific_rematching": False,
        "regime_specific_rematching": False,
        "case_specific_rematching": False,
        "same_index_semantic_alignment_assumed": False,
        "weighted_stability_score": False,
        "best_seed_selected": False,
        "best_head_selected": False,
        "head_pruning": False,
        "head_ablation": False,
        "model_training": False,
        "new_test_inference": False,
        "new_attention_extraction": False,
        "causal_claim": False,
        "feature_importance_claim": False,
        "post_test_model_tuning": False,
        "phase58_ready": True,
        "phase58_authorized": False,
        "phase59_context_ready": True,
        "phase59_authorized": False,
        "warnings": warnings,
        "overall_status": overall_status,
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    fp.write_text(json.dumps(obj, indent=2, ensure_ascii=False, default=str))


def write_report(fp: Path, sources, **kwargs) -> None:
    fp.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Phase 57 — Seed-Stability Attention Check Report",
        "",
        "## 1. Objective",
        "",
        "Phase 57 quantifies whether the temporal-attention patterns of the Final Transformer remain stable across the three official final seeds (42 / 123 / 2026), once the head permutation problem is handled correctly. Two parallel views are reported:",
        "",
        "- **S57-A**: permutation-invariant layer head-mean stability (mean over heads first, then compare across seeds).",
        "- **S57-B**: permutation-aware matched-head stability, using a deterministic canonical JSD matching within each encoder layer.",
        "",
        "## 2. Why head permutation matters",
        "",
        "In Multi-Head Attention, heads in the same encoder layer do not have fixed semantic labels. Two independently trained models can learn similar roles but place them in different head indices. Same-index comparisons across seeds are NOT assumed to be semantically equivalent.",
        "",
        "## 3. Frozen sources and three-seed contract",
        "",
        f"- Seeds: {list(SEEDS)} (immutable).",
        f"- Anchor seed = {ANCHOR_SEED} (anchor reason: {ANCHOR_REASON}). Anchor is NOT performance-based.",
        f"- Layers: {NUM_LAYERS}; Heads: {NUM_HEADS}; Lookback: 72 steps (720 min = 12h).",
        f"- Final lock SHA: `{sources.final_lock_sha256[:16]}...`",
        f"- Test population SHA: `{sources.test_population_sha256[:16]}...`",
        "",
        "## 4. Permutation-invariant layer head-mean stability",
        "",
        "Mean profiles and per-target vectors are compared across all three seed pairs (42-123, 42-2026, 123-2026) using JSD, L1, L2, cosine, Pearson, Spearman, Wasserstein (minutes). No threshold invented; exact values reported.",
        "",
        "## 5. Per-target layer attention stability",
        "",
        "Per-target layer head-mean vectors are compared across all seed pairs. Distribution summaries (N / mean / SD / median / percentiles) are reported, not iid confidence intervals.",
        "",
        "## 6. Canonical head-matching methodology",
        "",
        "- Representation: full-Test mean last-query temporal profile per (seed, layer, head).",
        "- Cost: JSD (natural log), range [0, ln(2)].",
        "- Search: exhaustive enumeration of all H! permutations under the locked H2/H4 protocol (24 perms per layer per pair for H=4).",
        "- Tie-break: minimum total JSD -> minimum total Wasserstein (minutes) -> lexicographically smallest permutation.",
        f"- MATCH_TIE_TOL = {MATCH_TIE_TOL} (frozen before any computation).",
        "",
        "## 7. Matching cost matrices",
        "",
        "Cost matrices are stored in `head_matching_cost_matrices.csv` for every (layer, seed_pair, head_a, head_b). Canonical assignments are highlighted.",
        "",
        "## 8. Matching ambiguity and edge margins",
        "",
        "Best total JSD, second-best total JSD, assignment gap, edge margins are recorded for every (layer, seed_pair). Matches within MATCH_TIE_TOL trigger `ambiguous_match_warning`.",
        "",
        "## 9. Cycle-consistency audit",
        "",
        "Direct 123-2026 mapping vs anchor-induced 123-42-2026 mapping. Per-head boolean + per-layer fraction are recorded.",
        "",
        "## 10. Wasserstein matching sensitivity",
        "",
        "Wasserstein-only matching is computed independently. Agreement fraction with canonical JSD matching is reported. Wasserstein never replaces canonical JSD.",
        "",
        "## 11. Canonical three-seed matched-head groups",
        "",
        "Anchored at seed42. Each (layer, group) records (seed42_head, seed123_head, seed2026_head, ambiguity flags, cycle-consistent flag).",
        "",
        "## 12. Matched-head mean-profile stability",
        "",
        "Three pairwise stability views per matched group; consensus profiles (mean of three seeds) with sum ~1 audit.",
        "",
        "## 13. Matched-head per-target stability",
        "",
        "Frozen global mapping reused for every Test target. No target-specific rematch.",
        "",
        "## 14. Matched-head metric/top1 stability",
        "",
        "Six CORE_ATTENTION_METRICS-v1 compared across matched heads; top1 lag distribution TVD + JSD + modal-lag agreement.",
        "",
        "## 15. Dense worst-case full-map stability",
        "",
        "Frozen Phase 51 cases, raw [L,L] matrices, rowwise JSD + cosine + normalized Frobenius. NO PNG/image-pixel similarity. Selection-conditioned caveat documented.",
        "",
        "## 16. Error-conditioned layer-level stability",
        "",
        "Primary error-effect robustness view. Phase 56 layer-head-mean effects compared across seeds for Spearman / HIGH-LOW Cliff's / HIGH-LOW median delta / shared cohort / profile JSD / profile Wasserstein.",
        "",
        "## 17. Error-conditioned matched-head stability",
        "",
        "Secondary. Phase 56 per-head effects reindexed to canonical matched groups. Ambiguity warnings propagated.",
        "",
        "## 18. Shared-cohort seed consistency",
        "",
        "Identical target IDs across seeds → directly comparable effect magnitudes.",
        "",
        "## 19. Prediction-spread vs attention-disagreement analysis",
        "",
        "Secondary diagnostic. Spearman between Phase 48 prediction range/SD and layer mean-pairwise attention disagreement. No causal claim.",
        "",
        "## 20. Main attention robustness findings",
        "",
        f"Total findings: {len(kwargs.get('findings_rows', []))}.",
        "",
        "## 21. Why no best seed/head is selected",
        "",
        "All three seeds are official stochastic realizations. Cross-seed head semantic alignment is NOT assumed.",
        "",
        "## 22. Why attention stability is not functional equivalence",
        "",
        "Stable attention weights do not prove stable value (V) projections or functional contribution. The matching operates on full-Test mean last-query profiles only.",
        "",
        "## 23. Why stability is not causal explanation",
        "",
        "Stable error-attention association does not establish causal mechanism.",
        "",
        "## 24. Three-seed limitation",
        "",
        "Only three seeds; mean/SD across seeds describe the chosen stochastic realizations, not the full seed population.",
        "",
        "## 25. Handoff to Final Tables",
        "",
        "Phase 58 (Final Tables) is handoff-ready with frozen attention robustness evidence.",
        "",
        "## 26. Definition of Done",
        "",
        "- All three seed sources verified.",
        "- Layer head-mean + per-target stability complete.",
        "- Canonical JSD matching complete with ambiguity + cycle + sensitivity audits.",
        "- Matched-head stability + dense-case stability complete.",
        "- Error-effect layer + matched-head stability complete.",
        "- Prediction-spread secondary association complete.",
        "- No best seed/head; no pruning; no ablation; no retraining.",
        "- Phase 58 handoff ready; Phase 59 context ready.",
    ]
    fp.write_text("\n".join(lines), encoding="utf-8")


def write_readme(fp: Path, sources) -> None:
    fp.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Phase 57 — README (Seed-Stability Attention Check)",
        "",
        "## Why same-index heads cannot be assumed equivalent",
        "",
        "In Multi-Head Attention, heads in the same encoder layer have no fixed semantic label. Two independently trained models can learn similar roles but assign them to different head indices. Same-index diagnostic comparisons are explicitly flagged as `semantic_alignment_not_guaranteed`.",
        "",
        "## Why layer head-mean is permutation-invariant",
        "",
        "Averaging over heads within a layer FIRST (before cross-seed comparison) removes the head-index issue. This is the primary robust cross-seed stability view in Phase 57 (S57-A).",
        "",
        "## Why JSD is the canonical matching cost",
        "",
        "JSD is symmetric, bounded [0, ln(2)], designed for probability distributions, and already used in Phase 55. It does NOT depend on forecast error.",
        "",
        "## Why H2/H4 allows exhaustive permutation matching",
        "",
        "Under the locked H2/H4 protocol, the canonical Final Transformer architecture uses H=4 heads. With H=4, exhaustive enumeration of all 4! = 24 permutations is fully tractable.",
        "",
        "## How the deterministic tie-break works",
        "",
        f"(1) minimum total JSD; (2) if tied within MATCH_TIE_TOL = {MATCH_TIE_TOL}, minimum total Wasserstein (minutes); (3) if still tied, lexicographically smallest permutation.",
        "",
        "## Why seed42 is only an alignment anchor",
        f"Seed42 is the first predeclared final seed (`ANCHOR_REASON = {ANCHOR_REASON}`). It is NOT selected because it has lower Test RMSE, cleaner attention, or better matching.",
        "",
        "## What matching ambiguity means",
        "",
        "When multiple permutations produce total JSD within MATCH_TIE_TOL of the minimum, an ambiguous-match warning is recorded. Ambiguity is a legitimate stability finding, not a methodological failure.",
        "",
        "## What cycle consistency means",
        "",
        "Cycle consistency compares the direct 123-2026 mapping against the anchor-induced 123-42-2026 mapping. Inconsistency indicates that head identities are weakly identifiable across seeds.",
        "",
        "## Why Wasserstein matching is sensitivity-only",
        "",
        "Wasserstein-only matching is computed independently. Agreement with canonical JSD is reported. Wasserstein never replaces canonical JSD, regardless of how the result looks.",
        "",
        "## Why matching is frozen before error-conditioned analysis",
        "",
        "Freezing the matching SHA BEFORE applying Phase 56 effects prevents outcome-conditioned alignment (which would inflate apparent stability).",
        "",
        "## How per-target matched-head stability is computed",
        "",
        "The same global frozen mapping is applied to every Test target. NO target-specific rematching.",
        "",
        "## Why dense-case stability is supplementary",
        "",
        "Dense-case attention is only available for the frozen Phase 51 worst-case set. The dense case set is enriched for shared hard cases, so dense-case stability is selection-conditioned, not unbiased full-Test stability.",
        "",
        "## Why error-conditioned stability prioritizes layer head-mean",
        "",
        "Layer head-mean averages over heads FIRST, removing permutation. This avoids the ambiguity-propagation chain that matched-head results carry when head matching is weak.",
        "",
        "## Why prediction-attention disagreement is non-causal",
        "",
        "Both quantities are co-observed outcomes of the same forward pass + attention extraction. Correlation does not establish that attention instability CAUSED prediction instability.",
        "",
        "## Why no stability score/best seed/best head is created",
        "",
        "Weighted overall stability scores, ad-hoc stable/unstable thresholds, and best-seed/best-head selection are all explicitly forbidden. Stability is reported as transparent, separate evidence.",
        "",
        "## Forbidden actions summary",
        "",
        "- training, fine-tune, optimizer.step, scaler.fit",
        "- new Test inference; new attention extraction",
        "- destructive overwrite of any Phase 47-56 canonical artifact",
        "- best-seed/head selection; ensemble; weighted overall stability score",
        "- head ranking, pruning, ablation, clustering",
        "- target-specific, error-specific, regime-specific, case-specific rematching",
        "- anchor change after seeing results",
        "- Wasserstein replacing canonical JSD mapping post hoc",
        "- Test error cohort used as deployment regime",
        "- attention = feature importance / causal explanation / functional equivalence proof",
        "- cartesian subgroup mining",
        "- reading PNG pixels for numeric attention values",
        "- implementing Phase 58 / 59 (handoff files only)",
        "- notebook modification in this run",
    ]
    fp.write_text("\n".join(lines), encoding="utf-8")


def write_processing_log(fp: Path, sources, **kwargs) -> None:
    fp.parent.mkdir(parents=True, exist_ok=True)
    obj = {
        "phase": 57,
        "phase_name": "Seed-stability attention check",
        "version": PHASE57_VERSION,
        "corrective": True,
        "previous_version_archived": "SEED_STABILITY_ATTENTION-v1",
        "started_at": kwargs.get("started_at"),
        "completed_at": kwargs.get("completed_at"),
        "result": {
            "seeds": list(SEEDS),
            "anchor_seed": int(ANCHOR_SEED),
            "anchor_reason": ANCHOR_REASON,
            "performance_based_anchor": False,
            "final_lock_sha256": sources.final_lock_sha256,
            "test_population_sha256": sources.test_population_sha256,
            "phase47_canonical_test_population_sha256": sources.phase47_canonical_test_population_sha256,
            "phase52_attention_target_order_sha256": sources.phase52_attention_target_order_sha256,
            "raw_last_query_seed42_sha256": sources.raw_last_query_seed42_sha256,
            "raw_last_query_seed123_sha256": sources.raw_last_query_seed123_sha256,
            "raw_last_query_seed2026_sha256": sources.raw_last_query_seed2026_sha256,
            "raw_attention_sha": sources.raw_last_query_sha,
            "target_order_sha": sources.target_order_sha,
            "dense_case_order_sha": sources.dense_case_order_sha,
            "p54_signoff_sha": sources.p54_signoff_sha,
            "p54_version": PHASE54_VERSION,
            "p55_signoff_sha": sources.p55_signoff_sha,
            "p55_version": PHASE55_VERSION,
            "p55_handoff_sha": sources.p55_handoff_sha,
            "p56_signoff_sha": sources.p56_signoff_sha,
            "p56_version": PHASE56_VERSION,
            "p56_handoff_sha": sources.p56_handoff_sha,
            "prediction_seed_spread_sha": sources.prediction_seed_spread_sha,
            "artifacts_written": kwargs.get("artifacts_written", []),
            "figures_written": kwargs.get("figures_written", []),
            "findings_count": kwargs.get("findings_count", 0),
            "discrepancy_count": kwargs.get("discrepancy_count", 0),
            "warnings": kwargs.get("warnings", []),
            "overall_status": kwargs.get("overall_status", "PASS"),
        },
    }
    fp.write_text(json.dumps(obj, indent=2, ensure_ascii=False, default=str))
